data:
  path: "./data"

train:
  # 하이퍼파라미터 설정
  num_epochs: 10
  learning_rate: 0.005
  input_size: 2
  hidden_size: 128
  num_layers: 3
  output_size: 1

#model:
# pretrained: true

logging:
  level: INFO
  file: "./logs/train.log"

checkpoint:
  directory: "./checkpoints"
  save_interval: 5
